### ISSUE TITLE
Package doesn't work

### ISSUE THREAD

**Issue by jakubsuchybio** [laughk/Keypirinha-GitHub#1]
After creating token like this:
![image](https://user-images.githubusercontent.com/6567287/179207270-77322784-719c-4007-8103-dbea507e3977.png)
and setting it into github.ini like this:
![image](https://user-images.githubusercontent.com/6567287/179207405-f909c5a8-bddd-40e6-9ec8-2318a39c6d39.png)
Then I get this in console:
```
12:33:23.362 ** ERROR: github.github: HTTP Error 401: Unauthorized
12:33:23.364 ** ERROR: Error from github.github.on_suggest: <class 'ValueError'>: suggestions arg must be a list or a tuple
Traceback (most recent call last):
  File "C:\Users\jakub\AppData\Roaming\Keypirinha\InstalledPackages\github.keypirinha-package\github.py", line 79, in on_suggest
  File "C:\ProgramData\chocolatey\lib\keypirinha\tools\Keypirinha\python\site\keypirinha.py", line 938, in set_suggestions
    raise ValueError("suggestions arg must be a list or a tuple")
```

**Comment by ktunprasert** [comment]
I restarted Keypirinha.exe and it worked
